#!/usr/bin/env bash 

original_dir=$(pwd)

max_levels=10
levels_searched=0

if [[ -z $1 ]]; then
  echo "No directory provided."
  return
fi

while :
do 
  search_dir=$(find ~+ -maxdepth 1 -name $1 -type d)
  if [[ "$PWD" = "/" ]] || [[ $levels_searched = $max_levels ]]; then
    echo "Directory not found."
    cd $original_dir
    break
  fi

  if [[ -n $search_dir ]]; then 
    cd $original_dir
    cd $search_dir
    break
  else
    ((levels_searched+=1))
    cd ..
  fi
done
